Question 1:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated
sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24

In [11]:
import math
def calc_sqrt(a):
    lst1 = a.split(",")
    lst1 = [int(i) for i in lst1]
    out1 = []
    C = 50
    H = 30
    for D in lst1:
        Q = math.sqrt((2*C*D)/H)
        out1.append(str(int(Q)))
    out_string = ",".join(out1)
    print("The output is : ",out_string)


iv = input("Enter comma separated input sequence : ")
calc_sqrt(iv)

Enter comma separated input sequence : 100,150,180
The output is :  18,22,24


Question 2:

Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The
element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [32]:
import numpy as np

def generate_matrix(a):
    rows,cols = map(int,a.split(","))
    arr1 = np.zeros(shape=(rows,cols),dtype=int)
    for i in range(rows):
        for j in range(cols):
            arr1[i][j] = i*j
    
    print(arr1)

rows_cols = input("Enter the rows and columns (comma seperated) to create matrix : ")
generate_matrix(rows_cols)        

Enter the rows and columns (comma seperated) to create matrix : 3,5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


Question 3:

Write a program that accepts a comma separated sequence of words as input and prints the
words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world

In [35]:
def sort_words(a):
    lst1 = a.split(",")
    lst1.sort()
    sorted_Str = ','.join(lst1)
    print("The sorted string is : ",sorted_Str)
    

inp_Str = input("Enter a comma separated sequence of words as input : ")
sort_words(inp_Str)

Enter a comma separated sequence of words as input : without,hello,bag,world
The sorted string is :  bag,hello,without,world


Question 4:

Write a program that accepts a sequence of whitespace separated words as input and prints
the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world

In [41]:
def remove_duplicate_words(a):
    lst1 = a.split(" ")
    s = set(lst1)
    s = sorted(s)
    sorted_Str = ' '.join(s)
    print("The sorted string after removing duplicates is : ",sorted_Str)

inp_Str = input("Enter a space separated sequence of words as input : ")
remove_duplicate_words(inp_Str)

Enter a space separated sequence of words as input : hello world and practice makes perfect and hello world again
The sorted string after removing duplicates is :  again and hello makes perfect practice world


Question 5:

Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3

In [43]:
import re
def count_digits_alpha(str1):
    total_digits = len(re.findall('[0-9]',str1))
    total_alpha = len(re.findall('[A-z]',str1))
    print("LETTERS ",total_alpha)
    print("DIGITS ",total_digits)

inp_Str = input("Enter a string : ")
count_digits_alpha(inp_Str)

Enter a string : hello world! 123
LETTERS  10
DIGITS  3


Question 6:
A website requires the users to input username and password to register. Write a program to
check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them
according to the above criteria. 

Passwords that match the criteria are to be printed, each
separated by a comma.

Example

If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1

In [44]:
def validate_pass(str1):
    lst1 = str1.split(",")
    value = []
    for i in lst1:
        if len(i)< 6 and len(i) > 12:
            continue
        else:
            pass
        if not re.search("[a-z]",i):
            continue
        elif not re.search("[0-9]",i):
            continue
        elif not re.search("[A-Z]",i):
            continue
        elif not re.search("[$#@]",i):
            continue
        elif re.search("\s",i):
            continue
        else:
            pass
        value.append(i)
    print(",".join(value))
    

inp_Str = input("Enter the passwords with comma seperated : ")
validate_pass(inp_Str)

Enter the passwords with comma seperated : ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1
